### ISSUE TITLE
New maintainer for OnePlus 10 Pro

### ISSUE THREAD

**Issue by Arman-ATI** [RisingTechOSS-devices/official_devices#10]
## Device you want to apply for
```
OnePlus 10 Pro (wly)
```

## Email address
```
altafiarman5@gmail.com
```

## Device tree sources

```
https://github.com/ATI-labs/android_device_oneplus_wly/tree/rising
https://github.com/ATI-labs/android_device_oneplus_sm8450-common/tree/rising
https://github.com/ATI-labs/android_kernel_oneplus_sm8450
https://github.com/ATI-labs/android_kernel_oneplus_sm8450-modules
https://github.com/ATI-labs/android_kernel_oneplus_sm8450-devicetrees
https://github.com/ATI-labs/vendor_oneplus_wly
https://github.com/ATI-labs/vendor_oneplus_sm8450-common
https://github.com/ATI-labs/hardware_oplus
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Machad3xROMS/53778
```

## Other ROM's you maintain officially or unofficially
```
Project Everest (Official)(core team)
```

## Bugs on unofficial build
```
Oplus camera night mode is not working fine
```

## How long have you been building for?
```
1.5 Years
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Arman_ATI
```

**Comment by hipexscape** [comment]
https://github.com/ATI-labs/android_device_oneplus_sm8450-common/commit/d841c903b9a0370e99dd2227fea1a54876262260


????

**Comment by Arman-ATI** [comment]
Hello @hipexscape
thanks for reviewing my application
this commit improves the smoothness of scrolling and reduces memory usage it can also be found in other official device repos
if there are any problems with that commit I will drop that

**Comment by hipexscape** [comment]
> Hello @hipexscape thanks for reviewing my application this commit improves the smoothness of scrolling and reduces memory usage it can also be found in other official device repos if there are any problems with that commit I will drop that

Does this exists on rising os source ?

**Comment by Arman-ATI** [comment]
@hipexscape nvm however I removed it was leftover from our old base

**Comment by RisenID** [comment]
Hey,
Is there a reason as to why kernel modules are in a seperate repo, rather than in the kernel source directly?

**Comment by Arman-ATI** [comment]
> Hey, Is there a reason as to why kernel modules are in a seperate repo, rather than in the kernel source directly?

Hello,
Since the Oplus sm8450, developers have made all phones with a separate kernel and There is no actual reason for that, and I have not changed it.
this change can be found in sm8550 and sm8650 as well

**Comment by hipexscape** [comment]
Looks fine from my side 
@RisenID @manidweep please check

**Comment by hipexscape** [comment]
@Arman-ATI please contact me on telegram, username is same as my GitHub id
