### ISSUE TITLE
New maintainer Garnet (Xiaomi Redmi Note 13 Pro 5G)

### ISSUE THREAD

**Issue by chuspita** [RisingTechOSS-devices/official_devices#11]
## Device you want to apply for
```
Xiaomi Redmi Note 13 Pro 5G
```

## Email address
```
kosecki99@gmail.com
```

## Device tree sources

```
https://github.com/Garnet-Essence/device_xiaomi_garnet
https://github.com/Garnet-Essence/kernel_xiaomi_illusionX
https://github.com/Garnet-Essence/vendor_xiaomi_garnet
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
InfinityX and Afterlife
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Years
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes, because in Garnet Xiaomi did not fully release the code for the kernel, we are with gki kernel
```

### Telegram username
```
@franlop77
```

**Comment by manidweep** [comment]
already reserved

**Comment by manidweep** [comment]
approved from my end, @RisenID @hipexscape check from your end

**Comment by hipexscape** [comment]
Approved from my end also

**Comment by hipexscape** [comment]
As per the info, this guy has deleted his repos and send a message on tg that he got a new device.

Hence closing this issue
