### ISSUE TITLE
New maintainer Garnet (Xiaomi Redmi Note 13 Pro 5G/Poco X6 5G)

### ISSUE THREAD

**Issue by kibria5** [RisingTechOSS-devices/official_devices#14]
## Device you want to apply for
```
Xiaomi Redmi Note 13 Pro 5G/Poco X6 5G (Garnet)
```

## Email address
```
mdkibria687@gmail.com
```

## Device tree sources
```
https://github.com/kibria5/android_device_xiaomi_garnet.git
https://github.com/kibria5/android_device_xiaomi_garnet-kernel.git
https://github.com/kibria5/android_vendor_xiaomi_garnet.git
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
PixelStar
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
 3 years+
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
yes. Cause xiaomi release broken kernel source
```

### Telegram username
```
@kibria5
```

**Comment by manidweep** [comment]
can you tell me why u rebased everything rather than just pick a tree and commit on top of it?
cause i see the commits that u did , were also committed long back by other devs
u did a rebase i get that but why?

**Comment by kibria5** [comment]
> can you tell me why u rebased everything rather than just pick a tree and commit on top of it? cause i see the commits that u did , were also committed long back by other devs u did a rebase i get that but why?

I rebased my whole trees and removed some changes and fixes what i did I don't want anyone to get it l. here i just keep those changes what needed for A15 rom works properly

**Comment by manidweep** [comment]
"I dont want anyone to get it"?
how does this make sense
i just asked you the reason?
why getting rude about it?

**Comment by kibria5** [comment]
> "I dont want anyone to get it"? how does this make sense i just asked you the reason? why getting rude about it?

ah Sorry i didn't say it rudely,I was just trying to explain that I don’t want it shared.

**Comment by hipexscape** [comment]
> "I dont want anyone to get it"? how does this make sense i just asked you the reason? why getting rude about it?

Garnet community internal issues.

We should not interfere in that.

**Comment by donjohanliebert** [comment]
> > "I dont want anyone to get it"? how does this make sense i just asked you the reason? why getting rude about it?
> 
> Garnet community internal issues.
> 
> We should not interfere in that.

I agree to this.

**Comment by joshuah345** [comment]
no issues or concerns on my end 
+1

**Comment by hipexscape** [comment]
Looks fine to me 

+1

**Comment by hipexscape** [comment]
Hey @kibria5,

Please send a dm to me on telegram 

My username - hipexscape 

Regards,
@hipexscape
