### ISSUE TITLE
New maintainer for Nothing Phone 2 (Pong)

### ISSUE THREAD

**Issue by neikos4962** [RisingTechOSS-devices/official_devices#16]
## Device you want to apply for
```
Nothing Phone 2 (Pong) 
```

## Email address
```
alexandrusemina8@gmail.com
```

## Device tree sources

```
https://github.com/alexandrusemina/android_device_nothing_Pong.git
https://gitea.com/alexandrusemina/android_vendor_nothing_Pong.git
https://github.com/alexandrusemina/android_kernel_nothing_sm8475.git
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
DerpFest official
```

## Bugs on unofficial build
```
Lawnchair crashing so not included on build until a fix is found
```

## How long have you been building for?
```
3,5 years
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
semialex16
```

**Comment by hipexscape** [comment]
https://github.com/RisingTechOSS-devices/official_devices/issues/12


Someone has already applied
