### ISSUE TITLE
Poco X3 Pro

### ISSUE THREAD

**Issue by Opa2021** [RisingTechOSS-devices/official_devices#3]
Hi,ich würde gerne auf die 6.0 Rising installieren auf mein Poco x3 pro.can you send Download Link Sendung.

Thal you

**Comment by Opa2021** [comment]
Pleace

**Comment by manidweep** [comment]
this is for maintainership
why are you typing here when the release isnt even announced

**Comment by eun0115** [comment]
not a place to ask device support, please proceed to your community. i will close this issue
