### ISSUE TITLE
Moto Edge 30 (dubai)

### ISSUE THREAD

**Issue by Rakhshan7070** [RisingTechOSS-devices/official_devices#5]
## Device you want to apply for
```
Moto Edge 30 (Dubai)
```

## Email address
```
alirakhshan7070@gmail.com
```

## Device tree sources

```
https://github.com/Rakhshan7070/android_device_motorola_dubai
https://github.com/Rakhshan7070/android_device_motorola_sm7325-common
https://github.com/Rakhshan7070/proprietary_vendor_motorola_dubai
https://github.com/Rakhshan7070/proprietary_vendor_motorola_sm7325-common
https://github.com/Rakhshan7070/android_kernel_motorola_sm7325
```

## Link to the platform where you have released your unofficial build
```
https://github.com/Rakhshan7070/Dubai_builds_by_Rakhshan/releases
```

## Other ROM's you maintain officially or unofficially
```
CrDroid
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Months
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
shan_rakh
```

**Comment by RisenID** [comment]
Hey, it seems a lot of your builds have KSU built in. Could you explain why?

**Comment by Rakhshan7070** [comment]
@RisenID 
Yes, most of my builds have KSU built in because most users prefer KSU & they requested me to do so.
I saw the code of conduct & sure I won't build KSU if getting official.

**Comment by manidweep** [comment]
approved from my end, need 1 more for confirmation

**Comment by hipexscape** [comment]
Approved

**Comment by hipexscape** [comment]
Hey @Rakhshan7070,

Kindly contact me on telegram

Username:- hipexscape

Regards,
Abhinav Kumar
