### ISSUE TITLE
New maintainer for Xiaomi 12X (psyche)

### ISSUE THREAD

**Issue by Verevka** [RisingTechOSS-devices/official_devices#7]
## Device you want to apply for
```
Xiaomi 12X psyche
```

## Email address
```
vit187@yandex.ru
```

## Device tree sources

```
https://github.com/RisingOSS-psyche/device_xiaomi_sm8250-common
https://github.com/RisingOSS-psyche/device_xiaomi_psyche
https://github.com/RisingOSS-psyche/kernel_xiaomi_sm8250
https://github.com/RisingOSS-psyche/vendor_xiaomi_sm8250-common
https://github.com/RisingOSS-psyche/vendor_xiaomi_psyche
https://github.com/RisingOSS-psyche/hardware_xiaomi
https://github.com/RisingOSS-psyche/vendor_xiaomi_miuicamera
```

## Link to the platform where you have released your unofficial build
```
https://disk.yandex.ru/d/TlADKCRbcOSV2g
```

## Other ROM's you maintain officially or unofficially
```
https://www.androidfilehost.com/?fid=962021903579482204
https://www.androidfilehost.com/?fid=745849072291684273
https://www.androidfilehost.com/?fid=746010030569947986
https://www.androidfilehost.com/?fid=818070582850501456
https://www.androidfilehost.com/?fid=889964283620754708
https://www.androidfilehost.com/?fid=673368273298979954
https://disk.yandex.ru/d/z48ey-toJ3DxyQ
https://disk.yandex.ru/d/PVb5yp-v7ep-fQ

```

## Bugs on unofficial build
```
Miui Camera: hdr photo
```

## How long have you been building for?
```
~ 10 years
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
https://t.me/Verevka86
```

**Comment by RisenID** [comment]
Hey, the link shared for other roms you built goes to a page in your account settings, and thus cannot be viewed by anyone else. Please provide a proper answer for that question

**Comment by Verevka** [comment]
> Hey, the link shared for other roms you built goes to a page in your account settings, and thus cannot be viewed by anyone else. Please provide a proper answer for that question

I corrected it, gave a few examples, but that's not all.

**Comment by RisenID** [comment]
> > Hey, the link shared for other roms you built goes to a page in your account settings, and thus cannot be viewed by anyone else. Please provide a proper answer for that question
> 
> I corrected it, gave a few examples, but that's not all.

All the links for the examples you sent are for sagit and vayu. What have you done on the device that you are applying for?

**Comment by Verevka** [comment]
Psyche full work ) There are a couple of problems with the miuicamera, but I will close them too.

**Comment by RisenID** [comment]
> Psyche full work ) There are a couple of problems with the miuicamera, but I will close them too.

Sure, but i want to see the work you have done on this device and the builds you have done and tested well.

**Comment by Verevka** [comment]
> Sure, but i want to see the work you have done on this device and the builds you have done and tested well.

And how do I demonstrate that to you?

**Comment by RisenID** [comment]
> And how do I demonstrate that to you?

By showing me where you have released your work for this device, like for example an XDA post

**Comment by eun0115** [comment]
oops, my bad closing this.

**Comment by RisenID** [comment]
> By showing me where you have released your work for this device, like for example an XDA post

Due to lack of released builds to the community, your application is rejected. Please feel free to apply in the future
