### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Thereache** [RisingTechOSS-devices/official_devices#8]
## Device you want to apply for
```
Poco x5 pro 5G redwood 
```

## Email address
```
thereache2003@gmail.com
```

## Device tree sources

```
https://github.com/TRR-labs/android_device_xiaomi_redwood.git
https://github.com/TRR-labs/android_device_xiaomi_sm8350-common
https://github.com/TRR-labs/android_vendor_xiaomi_sm8350-common.git
https://github.com/TRR-labs/android_vendor_xiaomi_redwood.git
https://github.com/Thereache/kernel_xiaomi_redwood
```

## Link to the platform where you have released your unofficial build
```
https://t.me/thereachebuildchat/10385/10419
```

## Other ROM's you maintain officially or unofficially
```
Everest os/Pixelstar 
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1 Year
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
RushItz
```

**Comment by hipexscape** [comment]
Why dont you have any contribution on vendor repos ?

**Comment by Thereache** [comment]
sir vendor repo link is updated, I forgot to push my changes check the repo again , sorry about that

**Comment by RisenID** [comment]
Hey, we already have a RisingOS maintainer for redwood at this time. Due to this, your application is rejected.
